# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mpesa_transaction

test:
  <<: *default
  database: mpesa_transaction

production:
  <<: *default
  database: mpesa_transaction
  username: memetibryan
  password: <%= ENV['password'] %>
